export default[
  'Adidas',
  "Allstate",
  "Amazon",
  "Boeing",
  'Chipotle',
  'Comcast',
  "Costco",
  "Dunkin' Donuts",
  "Groupon",
  "IBM",
  'Jordan Brand',
  "McDonald's",
  "Microsoft",
  "Old Navy",
  "Pepsi",
  "Popeyes",
  "Procter & Gamble",
  "Puma",
  "Red Lobster",
  "Snapchat",
  "SoundCloud",
  "Starbucks",
  "Tidal",
  "Subway",
  "Uber",
  "Under Armour",
  "United",
  "Walgreens",
  "Walmart",
  "Victoria's Secret",
  "Verizon Wireless",
  "Whole Foods",
  "Add another brand!"]
